//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintArgsList) DeepCopyInto(out *ConstraintArgsList) {
	*out = *in
	if in.ResourceRange != nil {
		in, out := &in.ResourceRange, &out.ResourceRange
		*out = new(ResourceRangeArgs)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintArgsList.
func (in *ConstraintArgsList) DeepCopy() *ConstraintArgsList {
	if in == nil {
		return nil
	}
	out := new(ConstraintArgsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaximizeInequalityArgs) DeepCopyInto(out *MaximizeInequalityArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaximizeInequalityArgs.
func (in *MaximizeInequalityArgs) DeepCopy() *MaximizeInequalityArgs {
	if in == nil {
		return nil
	}
	out := new(MaximizeInequalityArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Planner) DeepCopyInto(out *Planner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Planner.
func (in *Planner) DeepCopy() *Planner {
	if in == nil {
		return nil
	}
	out := new(Planner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Planner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerList) DeepCopyInto(out *PlannerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Planner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerList.
func (in *PlannerList) DeepCopy() *PlannerList {
	if in == nil {
		return nil
	}
	out := new(PlannerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlannerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerSpec) DeepCopyInto(out *PlannerSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Constraints.DeepCopyInto(&out.Constraints)
	in.Preferences.DeepCopyInto(&out.Preferences)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerSpec.
func (in *PlannerSpec) DeepCopy() *PlannerSpec {
	if in == nil {
		return nil
	}
	out := new(PlannerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannerStatus) DeepCopyInto(out *PlannerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannerStatus.
func (in *PlannerStatus) DeepCopy() *PlannerStatus {
	if in == nil {
		return nil
	}
	out := new(PlannerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreferenceArgsList) DeepCopyInto(out *PreferenceArgsList) {
	*out = *in
	if in.Uniform != nil {
		in, out := &in.Uniform, &out.Uniform
		*out = new(UniformArgs)
		**out = **in
	}
	if in.MaximizeInequality != nil {
		in, out := &in.MaximizeInequality, &out.MaximizeInequality
		*out = new(MaximizeInequalityArgs)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreferenceArgsList.
func (in *PreferenceArgsList) DeepCopy() *PreferenceArgsList {
	if in == nil {
		return nil
	}
	out := new(PreferenceArgsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRangeArgs) DeepCopyInto(out *ResourceRangeArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRangeArgs.
func (in *ResourceRangeArgs) DeepCopy() *ResourceRangeArgs {
	if in == nil {
		return nil
	}
	out := new(ResourceRangeArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniformArgs) DeepCopyInto(out *UniformArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniformArgs.
func (in *UniformArgs) DeepCopy() *UniformArgs {
	if in == nil {
		return nil
	}
	out := new(UniformArgs)
	in.DeepCopyInto(out)
	return out
}
