apiVersion: v1
kind: Pod
metadata:
  name: sample2
  namespace: default
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
  tolerations:
  - key: "best"
    operator: "Equal"
    value: "yes"
    effect: "NoSchedule"
