---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.hse.ru
  resources:
  - planners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hse.ru
  resources:
  - planners/finalizers
  verbs:
  - update
- apiGroups:
  - apps.hse.ru
  resources:
  - planners/status
  verbs:
  - get
  - patch
  - update
