apiVersion: v1
kind: Pod
metadata:
  name: sample1
  namespace: default
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: sample2
  namespace: default
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: sample3
  namespace: default
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: sample4
  namespace: default
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:2.0
    resources:
      requests:
        memory: "600Mi"
        cpu: "600m"

